### ISSUE TITLE
bug: `options.language` is not reaactive

### ISSUE THREAD

**Issue by tresorama** [LeoDog896/svelte-monaco#2]
## What

Creating a `<Monaco>` instance, and a `<select>` for changing the `language`, **language change does not re-render the Monaco** component, resulting in language not changing in the editor.

```svelte
<script lang="ts">
  import Monaco from 'svelte-monaco';
  
  // Text value that is being edited
  let editorValue = ``;
  
  // Editor language
  const languages: { slug: string; label: string }[] = [
  { slug: 'js', label: 'JavaScript' },
  { slug: 'ts', label: 'TypeScript' },
  { slug: 'json', label: 'JSON' },
  { slug: 'css', label: 'CSS' },
  ];
  let language_slug = 'css';
</script>


<Monaco
  options={{
    language: language_slug,
    automaticLayout: true
  }}
  bind:value={editorValue}
/>

<select bind:value={language_slug}>
  {#each languages as language}
    <option value={language.slug}>{language.label}</option>
  {/each}
</select>

```

## Workaround

To force a re-render when `languague_slug` changes we can use [`svelte #key`](https://svelte.dev/repl/9bea8fa9846140d28444bece70fb7d27?version=3.38.2) feature.

```svelte
<script lang="ts">
  // ...
  let language_slug = 'css';
</script>

{#key language_slug}
  <Monaco
    options={{
	    language: language_slug,
	    automaticLayout: true
    }}
    bind:value={editorValue}
  />
{/key}

```

## Is this a real bug ?
This [part of the docs](https://github.com/LeoDog896/svelte-monaco#features) made me think this is a bug
> Reactive everywhere - two-way value binding with preserved cursor position, and reactive options.
  
  
But ,  
maybe it is expected behavior. If that is the case, my suggestion is to **include this scenario in the docs**

## PS
Thank you so much for this pacakge, it saves a lot of time! 🤩

**Comment by tristan-f-r** [comment]
Thanks for the issue! I'll check it out shortly - it is valid 👍.

**Comment by tresorama** [comment]
Tested `0.4.0`. It's working without svelte #key workaround.
Thanks @LeoDog896
